# -*- coding: utf-8 -*-
"""part1_grade_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m10WinWVpOIWQysI0LpOQvqjEOB_eKcC
"""

# Student Grade Tracker
# Name: Aarchi Aarchi
# Description: Handles student data, analysis, and reports
#TASK 1 - CLEANING DATA

raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma",       "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ",    "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA",       "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ",    "roll": "105", "marks_str": "75, 80, 70, 68, 85"},
]

for student in raw_students:
  name = student["name"].strip().title()
  roll = int(student["roll"])
  marks = list(map(int, student["marks_str"].split(", ")))
  valid = True
for word in name.split():
    if not word.isalpha():
        valid = False

if valid:
    print("✓ Valid name")
else:
    print("✗ Invalid name")

print("="*32)
print(f"Student : {name}")
print(f"Roll No : {roll}")
print(f"Marks   : {marks}")
print("="*32)

if roll == 103:
    print(name.upper())
    print(name.lower())

# TASK 2 - MARKS ANALYSIS

student_name = "Ayesha Sharma"
subjects     = ["Math", "Physics", "CS", "English", "Chemistry"]
marks        = [88, 72, 95, 60, 78]

for i in range(len(subjects)):
    m = marks[i]

    if m >= 90:
        grade = "A+"
    elif m >= 80:
        grade = "A"
    elif m >= 70:
        grade = "B"
    elif m >= 60:
        grade = "C"
    else:
        grade = "F"

    print(subjects[i], ":", m, "-", grade)

total = sum(marks)
avg = round(total / len(marks), 2)

print("Total:", total)
print("Average:", avg)

max_marks = max(marks)
min_marks = min(marks)

print("Highest:", subjects[marks.index(max_marks)], max_marks)
print("Lowest:", subjects[marks.index(min_marks)], min_marks)

count = 0

while True:
    subject = input("Enter subject (or 'done'): ")

    if subject.lower() == "done":
        break

    marks_input = input("Enter marks: ")

    if not marks_input.isdigit():
        print("Invalid marks")
        continue

    marks_val = int(marks_input)

    if marks_val < 0 or marks_val > 100:
        print("Marks must be 0-100")
        continue

    subjects.append(subject)
    marks.append(marks_val)
    count += 1

print("New subjects added:", count)
print("Updated average:", round(sum(marks)/len(marks), 2))

#TASK 3 - CLASS SUMMARY

class_data = [
    ("Ayesha Sharma",  [88, 72, 95, 60, 78]),
    ("Rohit Verma",    [55, 68, 49, 72, 61]),
    ("Priya Nair",     [91, 85, 88, 94, 79]),
    ("Karan Mehta",    [40, 55, 38, 62, 50]),
    ("Sneha Pillai",   [75, 80, 70, 68, 85]),
]

print("Name              | Average | Status")
print("----------------------------------------")
pass_count = 0
fail_count = 0
topper_name = ""
topper_avg = 0
total_avg_sum = 0
for name, marks in class_data:
    avg = round(sum(marks)/len(marks), 2)
    total_avg_sum += avg

    if avg >= 60:
        status = "Pass"
        pass_count += 1
    else:
        status = "Fail"
        fail_count += 1

    print(f"{name:<18} | {avg:<7} | {status}")

    if avg > topper_avg:
        topper_avg = avg
        topper_name = name
print("Passed:", pass_count)
print("Failed:", fail_count)

print("Topper:", topper_name, topper_avg)

class_avg = round(total_avg_sum / len(class_data), 2)
print("Class Average:", class_avg)

#TASK 4 - STRING MANIPULATION UTILITY

essay = "  python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning.  "

clean_essay = essay.strip()
print("Stripped:", clean_essay)

print("Title Case:", clean_essay.title())

count = clean_essay.count("python")
print("Python count:", count)

replaced = clean_essay.replace("python", "Python 🐍")
print(replaced)

sentences = clean_essay.split(". ")
print(sentences)

for i in range(len(sentences)):
    s = sentences[i]

    if not s.endswith("."):
        s += "."

    print(f"{i+1}. {s}")