# -*- coding: utf-8 -*-
"""part2_order_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtxHM0J-_DivKe_NXJ9EmpZ9A3VpVIm0
"""

#TASK 1 — MENU EXPLORATION

menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}

inventory = {
    "Paneer Tikka":   {"stock": 10, "reorder_level": 3},
    "Chicken Wings":  {"stock":  8, "reorder_level": 2},
    "Veg Soup":       {"stock": 15, "reorder_level": 5},
    "Butter Chicken": {"stock": 12, "reorder_level": 4},
    "Dal Tadka":      {"stock": 20, "reorder_level": 5},
    "Veg Biryani":    {"stock":  6, "reorder_level": 3},
    "Garlic Naan":    {"stock": 30, "reorder_level": 10},
    "Gulab Jamun":    {"stock":  5, "reorder_level": 2},
    "Rasgulla":       {"stock":  4, "reorder_level": 3},
    "Ice Cream":      {"stock":  7, "reorder_level": 4},
}

sales_log = {
    "2025-01-01": [
        {"order_id": 1,  "items": ["Paneer Tikka", "Garlic Naan"],          "total": 220.0},
        {"order_id": 2,  "items": ["Gulab Jamun", "Veg Soup"],              "total": 210.0},
        {"order_id": 3,  "items": ["Butter Chicken", "Garlic Naan"],        "total": 360.0},
    ],
    "2025-01-02": [
        {"order_id": 4,  "items": ["Dal Tadka", "Garlic Naan"],             "total": 220.0},
        {"order_id": 5,  "items": ["Veg Biryani", "Gulab Jamun"],           "total": 340.0},
    ],
    "2025-01-03": [
        {"order_id": 6,  "items": ["Paneer Tikka", "Rasgulla"],             "total": 260.0},
        {"order_id": 7,  "items": ["Butter Chicken", "Veg Biryani"],        "total": 570.0},
        {"order_id": 8,  "items": ["Garlic Naan", "Gulab Jamun"],           "total": 130.0},
    ],
    "2025-01-04": [
        {"order_id": 9,  "items": ["Dal Tadka", "Garlic Naan", "Rasgulla"], "total": 300.0},
        {"order_id": 10, "items": ["Paneer Tikka", "Gulab Jamun"],          "total": 270.0},
    ],
}

categories = set()

for item in menu:
    categories.add(menu[item]["category"])

for category in categories:
    print(f"\n===== {category} =====")

    for item, details in menu.items():
        if details["category"] == category:
            status = "Available" if details["available"] else "Unavailable"
            print(f"{item:<15} ₹{details['price']:.2f}   [{status}]")

total_items = len(menu)

available_items = 0
for item in menu:
    if menu[item]["available"]:
        available_items += 1

print("Total items:", total_items)
print("Available items:", available_items)

max_price = 0
max_item = ""

for item, details in menu.items():
    if details["price"] > max_price:
        max_price = details["price"]
        max_item = item

print("Most expensive:", max_item, max_price)

print("Items under ₹150:")

for item, details in menu.items():
    if details["price"] < 150:
        print(item, "-", details["price"])

# TASK 2 — CART SYSTEM

cart = []

def add_to_cart(item_name, qty):
    if item_name not in menu:
        print("Item does not exist")
        return

    if not menu[item_name]["available"]:
        print("Item not available")
        return

    # check if already in cart
    for item in cart:
        if item["item"] == item_name:
            item["quantity"] += qty
            return

    # new item
    cart.append({
        "item": item_name,
        "quantity": qty,
        "price": menu[item_name]["price"]
    })

def remove_from_cart(item_name):
    for item in cart:
        if item["item"] == item_name:
            cart.remove(item)
            return
    print("Item not in cart")

add_to_cart("Paneer Tikka", 2)
print(cart)

add_to_cart("Gulab Jamun", 1)
print(cart)

add_to_cart("Paneer Tikka", 1)
print(cart)

add_to_cart("Mystery Burger", 1)
add_to_cart("Chicken Wings", 1)

remove_from_cart("Gulab Jamun")
print(cart)

print("\n========== Order Summary ==========")

subtotal = 0

for item in cart:
    total_price = item["quantity"] * item["price"]
    subtotal += total_price

    print(f"{item['item']:<15} x{item['quantity']}   ₹{total_price:.2f}")

gst = subtotal * 0.05
total = subtotal + gst

print("------------------------------------")
print(f"Subtotal: ₹{subtotal:.2f}")
print(f"GST: ₹{gst:.2f}")
print(f"Total: ₹{total:.2f}")
print("====================================")

# TASK 3 — INVENTORY

import copy

inventory_backup = copy.deepcopy(inventory)

inventory["Paneer Tikka"]["stock"] = 0

print("Inventory:", inventory["Paneer Tikka"])
print("Backup:", inventory_backup["Paneer Tikka"])

inventory = copy.deepcopy(inventory_backup)

for item in cart:
    name = item["item"]
    qty = item["quantity"]

    if inventory[name]["stock"] < qty:
        print(f"Warning: Only {inventory[name]['stock']} available for {name}")
        inventory[name]["stock"] = 0
    else:
        inventory[name]["stock"] -= qty

for item, details in inventory.items():
    if details["stock"] <= details["reorder_level"]:
        print(f"⚠ Reorder Alert: {item} — Only {details['stock']} left")

# TASK 4 — SALES ANALYSIS

daily_revenue = {}

for date, orders in sales_log.items():
    total = 0
    for order in orders:
        total += order["total"]

    daily_revenue[date] = total
    print(date, ":", total)

best_day = max(daily_revenue, key=daily_revenue.get)
print("Best day:", best_day)

item_count = {}

for orders in sales_log.values():
    for order in orders:
        for item in order["items"]:
            item_count[item] = item_count.get(item, 0) + 1

most_ordered = max(item_count, key=item_count.get)
print("Most ordered item:", most_ordered)

sales_log["2025-01-05"] = [
    {"order_id": 11, "items": ["Butter Chicken", "Gulab Jamun", "Garlic Naan"], "total": 490.0},
    {"order_id": 12, "items": ["Paneer Tikka", "Rasgulla"], "total": 260.0},
]

count = 1

for date, orders in sales_log.items():
    for order in orders:
        items = ", ".join(order["items"])
        print(f"{count}. [{date}] Order #{order['order_id']} — ₹{order['total']} — Items: {items}")
        count += 1